### ISSUE TITLE
my app cant display this data

### ISSUE THREAD

**Issue by jeffryafandi** [vedfi/mondroid#10]
it leaves blank on the document viewer that contains this data:

{
  "_id": 0,
  "mobsArray": [],
  "shop": [
    {
      "_id": "jefffy",
      "stock": {
        "$numberDouble": "Infinity"
      },
      "price": 788,
      "type": "coupon"
    },
    {
      "_id": "sword",
      "stock": 3,
      "price": 12,
      "type": "coupon"
    }
  ],
  "__v": 2
}

**Comment by jeffryafandi** [comment]
![Screenshot_20230608-024413](https://github.com/vedfi/mondroid/assets/66934509/7ec9bf95-022d-4dc3-bfb7-4d5c819dfb29)
![Screenshot_20230608-024410](https://github.com/vedfi/mondroid/assets/66934509/e6c4d94f-e1b6-4e81-82df-d848bbb0e020)

here are some screenshots

**Comment by vedfi** [comment]
Hello Sir;

It seems like there is a problem with _id field. It must be an ObjectId. Your document has an Integer value in _id field.

**Comment by jeffryafandi** [comment]
hello thanks for the reply, isn't it's fine if the id is Integer as long as i declare it on mongo schema? 

sorry I quite new on this thing.. also it's worked on my string collection schema

**Comment by jeffryafandi** [comment]
![Screenshot_20230608-040028](https://github.com/vedfi/mondroid/assets/66934509/2284b868-2734-4a8d-b3d7-756dd773dc76)
i just changed the type and re creating my document and it's still blank

**Comment by jeffryafandi** [comment]
i guess it can't handle Infinity as Number??

**Comment by vedfi** [comment]
Actually Documents in MongoDB must have an _id member, which uniquely identifies the document within a collection. This _id value is type of an ObjectId by default. You can change its type to another. But Mondroid cannot update a document without an ObjectId. You can view your document in records page but you cannot modify it in editing page. 

I will be testing your data. Maybe there is a problem about Infinity like you said.

**Comment by jeffryafandi** [comment]
cool! thank your for your explanation..

hoping you to have a wonderful day...

**Comment by vedfi** [comment]
![Screenshot_20230608_001619.jpg](https://github.com/vedfi/mondroid/assets/29797832/c448f50c-5873-4e6c-a655-63b7e3a1d6c4)

![Screenshot_20230608_001625.jpg](https://github.com/vedfi/mondroid/assets/29797832/01a79f8f-0974-4746-b88c-88e50811dca2)

I created the document in mondroid, only changed _id value to an ObjectId instead of an Integer. It seems to be working fine. Also  Mondroid doesnt have an $numberDouble operator, so its considered as a string.

**Comment by jeffryafandi** [comment]
![Screenshot_20230608-042238](https://github.com/vedfi/mondroid/assets/66934509/c0acf407-3480-4857-9699-abe74d59ec61)
![Screenshot_20230608-042314](https://github.com/vedfi/mondroid/assets/66934509/ee0b4da1-4085-4ed0-bee0-86bf0c73d9f6)
![IMG_20230608_042326](https://github.com/vedfi/mondroid/assets/66934509/03bdc52e-9655-416e-8b5e-2abd3e553e00)

it's working fine but when i chenge the Number into Infinity it's all gone.. 

and the document still remain in my mongodb server

**Comment by jeffryafandi** [comment]
thanks for answering anyways, you should take a good sleep, isn't it midnight on your region?

**Comment by jeffryafandi** [comment]
oww found alternative to see what's inside my document, 
thank you for your screenshot, i haven't noticed that feature until few minutes ago.. haha

![IMG_20230608_043431](https://github.com/vedfi/mondroid/assets/66934509/2ab98463-6404-4990-951b-5a8ae7e56321)

**Comment by vedfi** [comment]
There is a bug with parsing Infinity values in jsonDecoder. I will be releasing a bugfix asap. Thx for your feedback.
