### ISSUE TITLE
How to connect to another collection?

### ISSUE THREAD

**Issue by Feskai** [vedfi/mondroid#12]
When connecting to mongo through the application, the "test" collection is created

Is it possible to change this value or connect to another existing collection?

**Comment by zuk4sa** [comment]
and cannot view existing database.

**Comment by vedfi** [comment]
Please make sure that your connection string is correct. You also have to specify the database name. Further information can be found in help section. (Create or edit connection tile, then in the popup menu; click to the question mark icon to open up help section)
