### ISSUE TITLE
Shows only 1 document in the collection

### ISSUE THREAD

**Issue by Tharusha-dev** [vedfi/mondroid#41]
The app only shows one document in a collection with 50 documents.
(I just coped the connection string from mongodb compess and pasted into the app)

![share_1542495212721035688](https://github.com/vedfi/mondroid/assets/90096115/99ecbb5f-1df4-49f3-9632-651d0b4464d4)

Mondroid version 1.0.8
Android 14

**Comment by vedfi** [comment]
Hello, this problem looks really strange.

To eliminate causes, can you create another collection with really simple documents inside of it using Mongodb Compass. (Like document with only one string field)

If newly created collections document count viewed correctly, then there is a really big problem with mongo-dart driver. 
If it still shows wrong, then there is a problem about authorization in your connection string. 

I will be waiting for your update.

**Comment by Tharusha-dev** [comment]
very sorry for the late reply. Turns out I forgot the whole "with database name" part of the URI. 

When I entered the uri as :

mongodb+srv://<credentials>@<cluster>.mongodb.net/<Database name>

all worked fine !

Adding something like an example URI to the README would help imo.
