### ISSUE TITLE
The document code is not displayed

### ISSUE THREAD

**Issue by AndroMaster436** [vedfi/mondroid#44]
When I open the collection itself, there is data in the document (and my server can safely read it). But in your client, the contents of the document are empty :(

Here is a screen recording showing the bug

https://github.com/vedfi/mondroid/assets/87223939/e954a970-9f00-471d-9903-b7174d3cffe6

**Comment by vedfi** [comment]
Hello, can you send the problematic document as json (copy from mongodb compass). There is probably an unsupported type error.

**Comment by AndroMaster436** [comment]
> Hello, can you send the problematic document as json (copy from mongodb compass). There is probably an unsupported type error.

{ "_id" : ObjectId("6623b679f90248a979ea0789"), "_accountId" : NumberLong(1), "_passToken" : "p2FHqyXhmSshIklGvJhhw0UNBZVoeifndmSEaENb", "_home" : { "_thumbnail" : 28000000, "_nameColor" : 43000000, "_experience" : 0, "_doubleCoins" : 0, "_unlockedSkins" : [ ], "_pendingRewardIndex" : 1 }, "_avatar" : { "_isDev" : true, "_name" : "LocalTest", "_duoWins" : 0, "_diamonds" : 999999, "_soloWins" : 0, "_trioWins" : 0, "_accountId" : NumberLong(1), "_heroes" : [ { "_new" : 0, "_score" : 0, "_cardId" : 23000000, "_skinId" : 29000000, "_starPower" : 0, "_powerLevel" : 1, "_characterId" : 16000000, "_powerPoints" : 0, "_highestScore" : 0 } ], "_nameSetByUser" : true } }

**Comment by AndroMaster436** [comment]
By the way, I tested one theory. A bug happens if the values in the class are private

![Screenshot_20240421-074042~2](https://github.com/vedfi/mondroid/assets/87223939/80a582b7-b050-4504-b6ad-ae68b0f5565f)

**Comment by vedfi** [comment]
Hello again can you copy document from mongodb compass with copy button. (I am sending a screenshot.)

![image](https://github.com/vedfi/mondroid/assets/29797832/71bb2778-050a-48d1-9d14-46edeb81b4b7)

Your document contains NumberLong() and ObjectId() sections. Compass doesn't allow me to insert your document. I've changed ObjectId() to "$oid": "" and long representation. (Screenshot given below.)

![image](https://github.com/vedfi/mondroid/assets/29797832/813fb96e-55de-4766-8163-e5e901bf0ae5)

I can view and modify document in Mondroid.

![Screenshot_20240421_213311](https://github.com/vedfi/mondroid/assets/29797832/2ec79f94-0ccd-466f-8238-52967a1f8a3e)
![Screenshot_20240421_213316](https://github.com/vedfi/mondroid/assets/29797832/885fbad1-1e42-4cb8-a4b9-2d89e3b57ef3)

**Comment by AndroMaster436** [comment]
I don't have atlas on the mongo website. I actually have a mongo server on
linux. I entered: db.Accounts.find() and I was given this json. Also look
at the theory that I sent about private objects in class

вс, 21 апр. 2024 г., 21:39 Ahmet YÜREKLİ ***@***.***>:

**Comment by vedfi** [comment]
Hello again, problem occurs when encoding int64 values to json. I will be adding Long/int64 data type support asap.
Thanks for your feedback.

**Comment by AndroMaster436** [comment]
In 1.0.9 fixed. Thanks

![Screenshot_20240423-063253](https://github.com/vedfi/mondroid/assets/87223939/fa223f4d-64a3-462d-9ba4-cb39bb384457)
