### ISSUE TITLE
HandshakeException

### ISSUE THREAD

**Issue by Domenicopezzullo** [vedfi/mondroid#54]
```
MongoDB ConnectionException: Could not connect to goat-shard-00-00.78ikd.mongodb.net:27017
- HandshakeException: Handshake error in client (OS Error: 
	TLSV1_ALERT_INTERNAL_ERROR(tls_record.cc:592))
```

I get this when trying to connect to the DB

**Comment by Domenicopezzullo** [comment]
I just had to whitelist the IP 😔

**Comment by vedfi** [comment]
Although it varies depending on the ISP you use, most of the time you need to whitelist your IP address. 
I'm glad to hear your issue has been resolved.
