### ISSUE TITLE
no collections in my database

### ISSUE THREAD

**Issue by VectorZhao** [vedfi/mondroid#9]
I have installed the latest apk file and linked to the Mongo database deployed on my VPS. However, I have encountered the same problem as #6.

![photo_2023-03-31 23 35 34](https://user-images.githubusercontent.com/16644993/229165665-c95fde09-32cd-40ad-96e1-e1283229f247.jpeg)

**Comment by vedfi** [comment]
Hello Sir,

Are you able to view collections with Mongodb Compass?
If so, make sure that you are using the exact same connection string in mondroid.

You may have to use authSource parameter like below;
mongodb://username:pwd@hostname:27017/yourDb?authSource=admin

Collections should be visible with the latest (v1.0.2) version; i have tested it.
